project: P2V-MAP
author: sebastian
version: 1.2
pipeline:
- data
- p2v
- tsne
config:
  data:
    variable_basket: basket_hash
    variable_values:
    - j
    batch_size: 1000
    shuffle: true
    n_negative_samples: 20
    power: 0.75
  p2v:
    p2v_kwargs:
      size: 15
      bias_negative_sampling: true
      product_bias_negative_sampling: false
      normalise_weights: false
      regularisation: null
      use_covariates: false
      optimizer:
        method: adam
        control:
          beta1: 0.9
          beta2: 0.999
          epsilon: 1e-08
      path_results: ./results/p2v-map-example
      n_batch_save: 1000
      n_batch_validation: 1000000
      n_batch_print: 1000
      n_products: 150
      verbose: 0
      train_streamer: null
      validation_streamer: null
      test_streamer: null
    p2v_train_kwargs:
      n_epoch: 5
      learning_rate: 0.0005
  tsne:
    tsne_data_kwargs:
      epoch: 4
      batch: 3000
      l2norm: true
      pca: null
      path_results: ./results/p2v-map-example
    tsne_kwargs:
      random_state: 1
      n_components: 2
      n_iter: 4000
      perplexity: 15
      init: pca
      angle: 0.5
      verbose: 0
